"""
Runtime Engine

Executes Task objects generated by the Planner.
"""

# Import the Capability Registry.
from vajra.capabilities.registry import CapabilityRegistry


class RuntimeEngine:
    """
    Executes Task objects generated by the Planner.
    """

    def __init__(self):
        """
        Initialise the Runtime Engine.

        The Runtime Engine owns a Capability Registry,
        which is used to locate the correct capability
        for each Task.
        """

        # Create the Capability Registry.
        self.registry = CapabilityRegistry()

    def execute(self, plan):
        """
        Execute an execution plan.

        Parameters:
            plan (list): List of Task objects.

        Returns:
            list: Execution results.
        """

        # Store the result of every executed task.
        results = []

        # Execute each task in sequence.
        for task in plan:

            # Retrieve the required capability.
            capability = self.registry.get_capability(task.capability)

            # If the capability is not registered,
            # skip the task and record the error.
            if capability is None:

                results.append(
                    f"Capability '{task.capability}' not found."
                )

                continue

            # Ask the capability to execute the task.
            result = capability.execute(task)

            # Store the execution result.
            results.append(result)

        # Return all execution results.
        return results