"""
Runtime Engine

Coordinates task execution by routing Tasks to the
appropriate Capability and recording execution history.
"""

from vajra.capabilities.registry import CapabilityRegistry
from vajra.memory.working.memory_manager import MemoryManager


class RuntimeEngine:
    """
    Executes execution plans generated by the Planner.
    """

    def __init__(self):
        """
        Initialise the Runtime Engine.
        """

        # Registry containing all available capabilities.
        self.registry = CapabilityRegistry()

        # Working Memory used to store execution history.
        self.memory = MemoryManager()

    def execute(self, plan):
        """
        Execute an execution plan.

        Parameters:
            plan (list): List of Task objects.

        Returns:
            list: Results produced by each executed task.
        """

        # Store execution results.
        results = []

        # Execute every task in the plan.
        for task in plan:

            # Find the required capability.
            capability = self.registry.get_capability(
                task.capability
            )

            # Capability not registered.
            if capability is None:

                error_message = (
                    f"Capability '{task.capability}' not found."
                )

                # Store failure in Working Memory.
                self.memory.add_memory(
                    memory_type="execution",
                    source="RuntimeEngine",
                    content=error_message,
                    metadata={
                        "task": task.action,
                        "capability": task.capability,
                    },
                    status="failed",
                )

                results.append(error_message)

                continue

            # Execute the task using the capability.
            result = capability.execute(task)

            # Store successful execution in Working Memory.
            self.memory.add_memory(
                memory_type="execution",
                source=capability.name,
                content=result,
                metadata={
                    "task": task.action,
                    "capability": task.capability,
                },
                status="success",
            )

            # Save the execution result.
            results.append(result)

        return results

    def get_execution_history(self):
        """
        Return all execution memories.

        Returns:
            list: Memory objects stored during execution.
        """

        return self.memory.get_all_memories()