"""
Runtime Engine

Coordinates task execution by routing Tasks to the
appropriate Capability, applying cognitive reasoning,
and recording execution history.
"""

from vajra.capabilities.registry import CapabilityRegistry
from vajra.memory.working.memory_manager import MemoryManager
from vajra.cognitive.reasoning.reasoning_engine import ReasoningEngine


class RuntimeEngine:
    """
    Executes execution plans generated by the Planner.
    """

    def __init__(self):
        """
        Initialise the Runtime Engine.
        """

        # Registry containing all available capabilities.
        self.registry = CapabilityRegistry()

        # Working Memory used to store execution history.
        self.memory = MemoryManager()

        # Cognitive Engine used for reasoning before execution.
        self.reasoning = ReasoningEngine()

    def execute(self, plan):
        """
        Execute an execution plan.

        Parameters:
            plan (list): List of Task objects.

        Returns:
            list: Results produced by each executed task.
        """

        results = []

        # Execute every task in the plan.
        for task in plan:

            # Find the required capability.
            capability = self.registry.get_capability(
                task.capability
            )

            # Capability not registered.
            if capability is None:

                error_message = (
                    f"Capability '{task.capability}' not found."
                )

                self.memory.add_memory(
                    memory_type="execution",
                    source="RuntimeEngine",
                    content=error_message,
                    metadata={
                        "task": task.action,
                        "capability": task.capability,
                    },
                    status="failed",
                )

                results.append(error_message)

                continue

            # -------------------------------------
            # Cognitive Layer
            # -------------------------------------

            # Generate thought and decision.
            thought, decision = self.reasoning.reason(task)

            # Store cognitive thought in memory.
            self.memory.add_memory(
                memory_type="thought",
                source=thought.source,
                content=thought.content,
                metadata=thought.metadata,
                status="success",
            )

            # Check decision approval.
            if not decision["approved"]:

                rejection_message = (
                    f"Task rejected: {decision['reason']}"
                )

                self.memory.add_memory(
                    memory_type="decision",
                    source="DecisionEngine",
                    content=rejection_message,
                    metadata={
                        "task": task.action,
                        "decision": decision["decision"],
                    },
                    status="failed",
                )

                results.append(rejection_message)

                continue

            # -------------------------------------
            # Execution Layer
            # -------------------------------------

            # Execute the task using capability.
            result = capability.execute(task)

            # Store execution result in memory.
            self.memory.add_memory(
                memory_type="execution",
                source=capability.name,
                content=result,
                metadata={
                    "task": task.action,
                    "capability": task.capability,
                    "decision": decision["decision"],
                },
                status="success",
            )

            results.append(result)

        return results

    def get_execution_history(self):
        """
        Return all execution memories.

        Returns:
            list: Memory objects stored during execution.
        """

        return self.memory.get_all_memories()