"""
Thought Object

Represents an internal thought generated by Vajra's
Cognitive Engine before making a decision.
"""

from datetime import datetime


class Thought:
    """
    Represents a single cognitive thought.
    """

    def __init__(
        self,
        thought_type,
        source,
        content,
        confidence=1.0,
        metadata=None,
    ):
        """
        Initialise a Thought object.

        Parameters:
            thought_type (str): Category of thought.
            source (str): Component creating the thought.
            content (str): Description of the thought.
            confidence (float): Confidence score.
            metadata (dict): Optional additional information.
        """

        self.timestamp = datetime.now()

        self.thought_type = thought_type

        self.source = source

        self.content = content

        self.confidence = confidence

        self.metadata = metadata or {}

    def __str__(self):
        """
        Human-readable representation.
        """

        return (
            f"[{self.timestamp}] "
            f"{self.thought_type} | "
            f"{self.source} | "
            f"{self.content} "
            f"(confidence={self.confidence:.2f})"
        )