"""
Vajra Adaptive Engine

Central intelligence layer responsible
for improving Vajra behaviour over time.

Responsibilities:

1. Receive reflections from completed tasks
2. Store learning experiences
3. Maintain adaptive state
4. Provide learning information
"""


class AdaptiveEngine:
    """
    Maintains Vajra's adaptive intelligence.

    Flow:

    Execution Result

          ↓

    Reflection Engine

          ↓

    Adaptive Engine

          ↓

    Learning History

          ↓

    Future Improvement
    """



    def __init__(
        self,
        reflection_engine=None,
        capability_ranker=None,
        strategy_manager=None
    ):
        """
        Initialize adaptive engine.


        Args:

            reflection_engine:
                Generates insights from results


            capability_ranker:
                Tracks capability performance


            strategy_manager:
                Maintains execution strategies
        """


        # Reflection component

        self.reflection_engine = (
            reflection_engine
        )


        # Capability ranking component

        self.capability_ranker = (
            capability_ranker
        )


        # Strategy management component

        self.strategy_manager = (
            strategy_manager
        )


        # Stores all learning experiences

        # Every successful or failed execution
        # reflection will be stored here.

        self.learning_history = []





    def learn(
        self,
        reflection
    ):
        """
        Update adaptive intelligence
        using execution reflection.


        Args:

            reflection:
                Insight generated by
                Reflection Engine
        """


        # Store latest learning event.

        # This becomes Vajra's experience
        # memory for future improvement.

        self.learning_history.append(
            reflection
        )





    def get_learning_state(
        self
    ):
        """
        Return current adaptive
        intelligence state.


        Used by:

        - Testing
        - Monitoring
        - Future Knowledge Layer
        """



        return {


            # Previous reflections

            "reflections":

                self.reflection_engine
                .get_reflections()
                if self.reflection_engine
                else [],



            # Capability performance ranking

            "capability_ranking":

                self.capability_ranker
                .get_ranking()
                if self.capability_ranker
                else [],



            # Current strategies

            "strategies":

                self.strategy_manager
                .get_all_strategies()
                if self.strategy_manager
                else [],



            # Historical learning events

            "learning_history":

                self.learning_history

        }